/* ===== Fifth Avenue Sushi — menu page generator =====
 *
 *   node build-menus.js
 *
 * Reads menu-data.js and rewrites the block between the
 * <!-- MENU:START --> and <!-- MENU:END --> markers in each
 * menus/<page>/index.html. Everything outside the markers is left alone.
 */

const fs = require('fs');
const path = require('path');
const MENU = require('./menu-data.js');

const esc = s => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/* Alt text carries the dish name and the restaurant — screen readers and image
   search both read this, and every file here is a plated dish shot. */
const alt = name => `${name} at Fifth Avenue Sushi, Calgary`;

/* The first photo on a page is the largest thing above the fold on a phone, so
   it loads eagerly at high priority — lazy-loading it delays LCP. Reset per page. */
let firstCard = true;

function card(item) {
  const desc = item.desc ? `\n        <p class="dish-card-desc">${esc(item.desc)}</p>` : '';
  const loading = firstCard
    ? 'loading="eager" fetchpriority="high"'
    : 'loading="lazy"';
  firstCard = false;
  return `      <article class="dish-card">
        <div class="dish-card-img">
          <img src="../../img/menu/${item.img}" alt="${esc(alt(item.name))}"
               width="600" height="800" ${loading} decoding="async">
        </div>
        <div class="dish-card-body">
          <h4 class="dish-card-name">${esc(item.name)}</h4>
          <span class="dish-card-price">$${item.price}</span>${desc}
        </div>
      </article>`;
}

function row(item) {
  const desc = item.desc ? `\n        <p class="dish-row-desc">${esc(item.desc)}</p>` : '';
  const pending = item.photoPending
    ? '\n        <span class="ph-tag ph-inline">Photo Pending</span>' : '';
  return `      <li class="dish-row">
        <div class="dish-row-main">
          <span class="dish-row-name">${esc(item.name)}</span>
          <span class="dish-row-dots" aria-hidden="true"></span>
          <span class="dish-row-price">$${item.price}</span>
        </div>${desc}${pending}
      </li>`;
}

function group(g) {
  const withPhoto = g.items.filter(i => i.img);
  const noPhoto = g.items.filter(i => !i.img);
  const id = slug(g.name);

  const parts = [`    <h3 class="dish-group-title" id="${id}-t">${esc(g.name)}</h3>`];
  if (g.note) parts.push(`    <p class="dish-group-note">${esc(g.note)}</p>`);
  if (withPhoto.length) {
    parts.push(`    <div class="dish-grid">\n${withPhoto.map(card).join('\n')}\n    </div>`);
  }
  if (noPhoto.length) {
    parts.push(`    <ul class="dish-rows">\n${noPhoto.map(row).join('\n')}\n    </ul>`);
  }

  return `  <section class="dish-group" id="${id}" aria-labelledby="${id}-t">
${parts.join('\n')}
  </section>`;
}

/* Chip nav — lets phone users jump between groups instead of scrolling
   past ~20 dishes. Only worth rendering when there's more than one group. */
function jumpNav(groups) {
  if (groups.length < 2) return '';
  const chips = groups
    .map(g => `    <a href="#${slug(g.name)}">${esc(g.name)}</a>`)
    .join('\n');
  return `  <nav class="dish-jump" aria-label="Jump to menu section">\n${chips}\n  </nav>\n`;
}

/* schema.org Menu — helps the menu surface in search results. */
function schema(page, data) {
  return JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Menu',
    name: data.title,
    url: `https://www.fifthavenuesushi.ca/menus/${page}/`,
    hasMenuSection: data.groups.map(g => ({
      '@type': 'MenuSection',
      name: g.name,
      hasMenuItem: g.items.map(i => ({
        '@type': 'MenuItem',
        name: i.name,
        ...(i.desc ? { description: i.desc } : {}),
        offers: { '@type': 'Offer', price: i.price, priceCurrency: 'CAD' }
      }))
    }))
  }, null, 2);
}

let changed = 0;
for (const [page, data] of Object.entries(MENU)) {
  const file = path.join(__dirname, 'menus', page, 'index.html');
  if (!fs.existsSync(file)) {
    console.error(`  skip  ${page} — no index.html`);
    continue;
  }

  firstCard = true;
  const html = fs.readFileSync(file, 'utf8');
  if (!html.includes('<!-- MENU:START -->')) {
    console.error(`  skip  ${page} — missing MENU:START marker`);
    continue;
  }

  const body = `<!-- MENU:START -->
<!-- Generated by build-menus.js from menu-data.js — edit that file, not this block. -->
<section class="menu-category-list menu-category-list-photo">
${jumpNav(data.groups)}${data.groups.map(group).join('\n\n')}
</section>
<script type="application/ld+json">
${schema(page, data)}
</script>
<!-- MENU:END -->`;

  const next = html.replace(
    /<!-- MENU:START -->[\s\S]*?<!-- MENU:END -->/,
    () => body
  );

  if (next !== html) {
    fs.writeFileSync(file, next);
    changed++;
  }
  const n = data.groups.reduce((a, g) => a + g.items.length, 0);
  const p = data.groups.reduce((a, g) => a + g.items.filter(i => i.img).length, 0);
  console.log(`  built ${page.padEnd(15)} ${String(n).padStart(3)} items (${p} with photos)`);
}
console.log(`\n${changed} page(s) written.`);
